### ISSUE TITLE
Typescript Definitions seems to be out of date

### ISSUE THREAD

**Issue by kilakewe** [fospitia/casbin-dynamodb-adapter#5]
With the 4.0 change to the adapter, the changes don't seem to be reflected in the typescript definition.

**Comment by hsluoyz** [comment]
@fospitia

**Comment by fospitia** [comment]
done, fixed in 0.4.1

**Comment by hsluoyz** [comment]
@fospitia thanks! https://github.com/fospitia/casbin-dynamodb-adapter/releases/tag/v0.4.1
